spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(ulgkaiGoxlqXMQU73WYgiseVmo6ELq/Cuyrlf+O9mb7eLfPsQB7QrI4L7kqv0mlujE7DbogiX3jwAnlTd/J6SmkvfyZ3f9Y8qTLqKT79C6ju4KWfwKLZRX3eM7WaC+RqUexfJvUyTG+lkz0+XA/n9g==)
    username: ENC(jZWb6BE+0stxAqjyk24nluJbR6VF2B7RRAegeefxBqCHGGSqA4kJ/kQ/3ONW5lI0)
    password: ENC(6XcyfocRPs90+nQ/MhuGsNmw9PFW+Nxs3kq90eLzhwHIUtDPhVgGZDD0q4Pb13rTKGZC5Ounc5Sl/RyPAL4SoA==)

  jpa:
    hibernate:
      # FIXME: 추후에 서비스 개발이 끝나고 배포 환경이 구성되면 validate 혹은 none으로 변경해야 함
      ddl-auto: create

  data:
    redis:
      host: redis
      port: 6379

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}
    username: Error Reporter
    avatar-url: https://i.imgur.com/uRkHXjk.png

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]

  endpoint:
    prometheus:
      enabled: true

    metrics:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true

aws:
  access-key: ENC(tRrfTq0vYJT1u3vpxM84nbTudTn76BvDa+SdMpPtnEG3hvnWdfsE1/JsAMaJmYQxt4wSeIFhU7bNNk9NUiullQ==)
  secret-key: ENC(tdUkOVbfi2GBLwfXKSgurrZIRArIsCV0eLZapwOWURRbqBXchqisS4F0erQpIbCtabdyBNxS9xTa9A/FlDrjtjyUZasfIsVZZdvvK1Pk1M8=)
  s3:
    region: ENC(u9xNdlCO2E+c+SOkV5wcv0pA2h3I5K5LGCy0qKmziQQJBop6PvKWpn6VZb35EJsv)
    bucket-name: ENC(rpTnDB2ZkrshPBDM1264vGh9ep8wZOfvsI0uHADuUdM/Qk/6uACA1ZgOEHFCEW2f)

oauth2:
  kakao:
    clientId: ENC(qhz/1p8n/EFFSF3APlmBYtiYGnokE0bYAxMSpSz0PTKeAgUN1+jTzGvgWGKdg+otmxXlRNRTYMyOe07XcviMpLkNruEnggMpLZnQE7Z4/fs=)
    redirect-uri: http://growup.kr/auth/kakao/callback
    accessToken-request-uri: https://kauth.kakao.com/oauth/token
    userinfo-request-uri: https://kapi.kakao.com/v2/user/me

  google:
    clientId: ENC(SLlWjeaquS7YGgH7mzJElBAvgdS2MnCWVA0yirq4k5M7x1rOrjdgo5IIGgcFDa4l6ymCNskT9wxXbq1lEHSpzxvmFaaz7dUtkC/DIEnbWMAGc3QhSoaqAUEBSwzbLqWdFc6Sl1kVSCLf9/S44EXOPg==)
    clientSecret: ENC(2yXpBIfVcAPv2REJ0Wi6FVE+dI+V12dYdKCTBJKFGIcQLzzDSXAv+RJ7A8sekg1iKE4hl6MSWQdkSbLBbKVyNqa65vxYT8pAHi0qatglCFE=)
    redirect-uri: https://growup.kr/auth/google/callback
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    accessToken-request-uri: https://oauth2.googleapis.com/token
    userinfo-request-uri: https://www.googleapis.com/oauth2/v2/userinfo
