spring:
  profiles:
    active: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(d5Va1G7shpJvPpTC35q15rSnH2uqMT4o8L21kbgbXOAvCsP7aj+XwMlgdBKXGXPjKQxcfe9h+4kV0NdQppIWyg==)
    password: ENC(uWGnnm8Cm5lR19AueV28RMpQhNIKqXo6X2xjrzQFYW186zwIu6feKH8lccI40vnFSfXNERiYe/MJ49Wqed4sHA==)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  application:
    name: grow-up-pms

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    whitelabel:
      enabled: false

jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: ${JASYPT_PASSWORD}

security:
  jwt:
    base64-secret: ENC(GsF8xZqjhZEphkvkgkKHDS23D6xo73+8iBGBJH1zSm1L9YBsHth1HdjMBivz3ljMSNTLDl+ZzlEw9UClhNemX+AmN0eVomJfo93VX6tZk5KWqAGhGk9X8hrCJnZluFFsjjMBd2+tJ13NHHigXpGxT+OxeziTgJWz0OP+vHLoNgQ=)
    access-token-expiration-millis: 900000
    refresh-token-expiration-millis: 604800000

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml

mailtrap:
  from: mailtrap@demomailtrap.com
